import './FormSelect.scss';

export function FormSelect({
                               name,
                               label,
                               onSelect,
                               placeholder,
                               value,
                               option1,
                               option2,
                               option3,
                               option4,
                               option5
                           }) {
    return (
        <div className="FormSelect">
            <label
                htmlFor={name}
                className="FormSelect-label"
            >
                {label}
            </label>
            <select
                className="FormSelect-select"
                name={name}
                id={name}
                onSelect={onSelect}
            >
                <option
                    className="FormSelect-select__option"
                    value=''
                    defaultValue=''
                >
                    {placeholder}
                </option>
                <option
                    className="FormSelect-select__option"
                    value={value}
                >
                    {option1}
                </option>
                <option
                    className="FormSelect-select__option"
                    value={value}
                >
                    {option2}
                </option>
                <option
                    className="FormSelect-select__option"
                    value={value}
                >
                    {option3}
                </option>
                <option
                    className="FormSelect-select__option"
                    value={value}
                >
                    {option4}
                </option>
                <option
                    className="FormSelect-select__option"
                    value={value}
                >
                    {option5}
                </option>
            </select>
        </div>
    )
}